bazel_dep(name = "ift_encoder", version = "git")
git_override(module_name = "ift_encoder", remote = "https://github.com/garretrieger/ift-encoder.git", commit = "de5346b06e3e6f63926b9ee94f80df81f65421df")
git_override(module_name = "ift_encoder_data", remote = "https://github.com/w3c/ift-encoder-data.git", commit = "cde4a492002e5a7523eee354ed0741a61a52e218")
